DROP TABLE IF EXISTS ROOM;
CREATE TABLE ROOM(
    ROOM_ID   INT AUTO_INCREMENT  PRIMARY KEY,
    NAME        VARCHAR(250) NOT NULL,
    ROOM_NUMBER CHAR(2)     NOT NULL UNIQUE,
    BED_INFO    CHAR(2)     NOT NULL
);